### PR TITLE
Fix issue #2

### PR DESCRIPTION
**Pull request by SewerRatMKWII**
Used the fix the error provided

### CODE REVIEW

**Comment by jayceslesar** [comment]
Hey @SewerRatMKWII awesome that you want to contribute as I am looking forward to making some cool tools with the community!  I do want to let you know that this change might have unintended outcomes, as specifying the `axis=1` like you have actually concatenated across the columns (horizontally) whereas here I am intending to concatenate across rows (vertically). This might not be an issue and could use a test/some testing. If you want to also submit a test with this pull request to prove that the data is staying the same before/after the change that would be awesome! Or if you think you can use the `.copy()` call to fix the issue that would also be another awesome approach!  Let me know if you have any questions!

**Comment by SewerRatMKWII** [comment]
@jayceslesar I have just made a new commit using the copy() approach

**Comment by SewerRatMKWII** [comment]
With this method the data wouldn't change

**Comment by jayceslesar** [comment]
Awesome !

**Review by jayceslesar — APPROVED** [review]

**Pull request merged**
